### ISSUE TITLE
There was a critical exception handling a packet on channel autoreglib

### ISSUE THREAD

**Issue by iamtpage** [Vazkii/AutoRegLib#11]
Hi,

I've been seeing several instances of this stacktrace in my server log

```
16:47:54] [Netty Epoll Server IO #15/ERROR] [FML]: There was a critical exception handling a packet on channel autoreglib
java.lang.UnsupportedOperationException: null
at net.minecraft.util.text.TextComponentBase.createBuilder(TextComponentBase.java:562) ~[he.class:?]
at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:695) ~[he.class:?]
at net.minecraft.util.text.TextComponentBase.toText(TextComponentBase.java:716) ~[he.class:?]
at org.spongepowered.common.text.SpongeTexts.toText(SpongeTexts.java:79) ~[SpongeTexts.class:1.12.2-2611-7.1.0-BETA-2916]
at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:50) ~[ChatUtil.class:1.12.2-2611-7.1.0-BETA-2916]
at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:4047) ~[oq.class:?]
at vazkii.quark.misc.feature.LockDirectionHotkey.setProfile(LockDirectionHotkey.java:207) ~[LockDirectionHotkey.class:?]
at vazkii.quark.base.network.message.MessageSetLockProfile.handleMessage(MessageSetLockProfile.java:21) ~[MessageSetLockProfile.class:?]
at vazkii.arl.network.NetworkMessage.onMessage(NetworkMessage.java:57) ~[NetworkMessage.class:?]
at vazkii.arl.network.NetworkMessage.onMessage(NetworkMessage.java:30) ~[NetworkMessage.class:?]
at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36) ~[SimpleChannelHandlerWrapper.class:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274) ~[minecraft_server.1.12.2.jar:?]
at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99) [FMLProxyPacket.class:?]
at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [gw.class:?]
at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [gw.class:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
```

MC: 1.12.2
Forge: forge-1.12.2-14.23.2.2611-universal
Autoreglib: AutoRegLib-1.3-15

**Comment by Scratchman** [comment]
I'm Having the same problem, I can't still on the server for more than a few minutes without being disconnected. If I move around I'm ok, but as soon as i stand still for more than a few minutes i get disconnected.

https://pastebin.com/gVjmtDTC

MC:1.12.2
Forge: forge-1.12.2-14.23.2.2611-universal
AutoRegLib-1.3-15
Quark-r1.4-122

I'm currently in the process of building a modpack for our server, so it's only in it's test phase, but i can't have this happen once the server launches.

**Comment by TheOpalium** [comment]
Got the exact same issue on my server.

There was a critical exception handling a packet on channel autoreglib
java.lang.UnsupportedOperationException: null
        at net.minecraft.util.text.TextComponentBase.createBuilder(TextComponentBase.java:562) ~[he.class:?]

Minecraft: 1.12.2
Forge: 14.23.4.2705
AutoRegLib: 1.3-18
Quark: r1.4-125

Apparently, the error started when one of the players enabled the Lock Rotation function. They lost connection a few seconds later, and then couldn't connect back until the server was restarted.

**Comment by LemADEC** [comment]
Issue is reproduced without Quark.
Is that library still maintained?

**Comment by LemADEC** [comment]
I don't see Sponge in the pastebin from Scratchman .

**Comment by gollariel** [comment]
I start seeing this problem after installing few new mods, and only when I jump... :
- Minecraft Transport Simulator
- Black Throne Empire Vehicle
- UNU Parts Pack
- MTS Seagulls

Without these mods problem is away...

**Comment by DeFazer** [comment]
The issue still persists with AutoRegLib-1.3-26. :<

**Comment by DeFazer** [comment]
The issue still persists with AutoRegLib-1.3-26. :<

**Comment by DesolateIntention** [comment]
I have the same problem but with EffortlessBuilding.

**Comment by strivenous** [comment]
still persists 
https://paste.gg/p/anonymous/8119cde9777e4192814343b1984ace8c

**Comment by darkgui157** [comment]
Did you solve this?

**Comment by darkgui157** [comment]
i have this problem but with ftb utilities and i cant solve :(... if you will help me, send me a message on wpp. +5584998028348

**Comment by tyon2006** [comment]
I'm also getting this issue with sponge. Have not found resolution yet.
