### ISSUE TITLE
Major Problem with New version of AutoRegLIb

### ISSUE THREAD

**Issue by TacticalUniverse** [Vazkii/AutoRegLib#21]
Crashes everyone back to Multiplayer menu 

java.lang.NoClassDefFoundError: vazkii/arl/util/ClientTicker
	at vazkii.psi.common.network.message.MessageTriggerJumpSpell.handleMessage(MessageTriggerJumpSpell.java:13) ~[MessageTriggerJumpSpell.class:?]
	at vazkii.arl.network.NetworkMessage.onMessage(NetworkMessage.java:57) ~[NetworkMessage.class:?]
	at vazkii.arl.network.NetworkMessage.onMessage(NetworkMessage.java:30) ~[NetworkMessage.class:?]

(edited)

**Comment by Vazkii** [comment]
Fixed by wire's PR.
