### ISSUE TITLE
Crash in dev environment

### ISSUE THREAD

**Issue by mezz** [Vazkii/AutoRegLib#5]
I tried testing some stuff by just dumping a whole pack of mods into my dev environment's `/mods/` folder, and got this crash:
`field_176227_L` is `Block.blockState`, I'm not sure why AutoRegLib is trying to get the obfuscated name.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  IC2core (industrialcraft-2-2.6.70-ex110.jar)
  LoadingPlugin (Quark-beta-49.jar)
  LoadingPlugin (sampler-1.67.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.31-dev.jar)
  LoadingPlugin (sneakyhost-8.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 9/25/16 5:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: field_176227_L
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:612)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:477)
	at net.minecraft.client.Minecraft.run(Minecraft.java:386)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
Caused by: java.lang.NoSuchFieldError: field_176227_L
	at vazkii.arl.block.BlockFacing.makeDefaultState(BlockFacing.java:34)
	at vazkii.arl.block.BlockFacing.<init>(BlockFacing.java:30)
	at vazkii.psi.common.block.BlockCADAssembler.<init>(BlockCADAssembler.java:41)
	at vazkii.psi.common.block.base.ModBlocks.init(ModBlocks.java:36)
	at vazkii.psi.common.core.proxy.CommonProxy.preInit(CommonProxy.java:44)
	at vazkii.psi.client.core.proxy.ClientProxy.preInit(ClientProxy.java:46)
	at vazkii.psi.common.Psi.preInit(Psi.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:599)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2269771640 bytes (2164 MB) / 3514826752 bytes (3352 MB) up to 7628390400 bytes (7275 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2094 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.10.2-12.18.1.2094-PROJECT(JustEnoughItems).jar) 
	UCH	Forge{12.18.1.2094} [Minecraft Forge] (forgeSrc-1.10.2-12.18.1.2094-PROJECT(JustEnoughItems).jar) 
	UCH	OpenComputers|Core{1.6.0.31-dev} [OpenComputers (Core)] (minecraft.jar) 
	UCH	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCH	tconstruct{1.10.2-2.5.2.jenkins357} [Tinkers' Construct] (TConstruct-1.10.2-2.5.2.jenkins357.jar) 
	UCH	immersiveengineering{0.10-42} [Immersive Engineering] (ImmersiveEngineering-0.10-42.jar) 
	UCH	JEI{3.9.999} [Just Enough Items] (JustEnoughItems_main) 
	UCH	ambidextrous{1.0} [Ambidextrous] (ambidextrous-1.0.jar) 
	UCH	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCE	Psi{r1.0-39} [Psi] (Psi-r1.0-39.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.0c.jar) 
	UCH	Baubles{1.3.BETA2} [Baubles] (Baubles-1.10.2-1.3.BETA2.jar) 
	UCH	BiomesOPlenty{4.1.0.2030} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2030-universal.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.9.4-2.0.0-38.jar) 
	UCH	BloodMagic{1.9.4-2.1.0-63} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-63.jar) 
	UCH	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
	UCH	mcmultipart{1.3.0_82} [MCMultiPart] (MCMultiPart-experimental-1.3.0_82-universal.jar) 
	UCH	CharsetLib{0.3.0-pre11} [‽] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetAudio{0.3.0-pre11} [♫] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetCarts{0.3.0-pre11} [U] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetDecoration{0.3.0-pre11} [�?] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetDrama{0.3.0-pre11} [!] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetFarming{0.3.0-pre11} [;] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetGates{0.3.0-pre11} [&] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetPipes{0.3.0-pre11} [|] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetStorage{0.3.0-pre11} [#] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetTweaks{0.3.0-pre11} [*] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetWires{0.3.0-pre11} [+] (Charset-0.3.0-pre11.jar) 
	UCH	CharsetWrench{0.3.0-pre11} [/] (Charset-0.3.0-pre11.jar) 
	UCH	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCH	chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
	UCH	combathelp{1.0.3} [Combat Help] (combathelp-1.9.4-1.0.3.jar) 
	UCH	IC2{2.6.70-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.70-ex110.jar) 
	UCH	CompactSolars{5.0.3.1} [Compact Solar Arrays] (CompactSolars-1.10-5.0.3.1-universal.jar) 
	UCH	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0.jar) 
	UCH	forestry{5.2.12.0} [Forestry] (forestry_1.10.2-5.2.12.0.jar) 
	UCH	ElecCore{1.5.311} [ElecCore] (ElecCore-1.9.4-1.5.311.jar) 
	UCH	OpenComputers{1.6.0.31-dev} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.31-dev.jar) 
	UCH	deepresonance{1.2.5} [DeepResonance] (deepresonance-1.10-1.2.5.jar) 
	UCH	endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.0_1.10_d92c1ee_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.0_1.10_d92c1ee_beta.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1-fc1-build-12.jar) 
	UCH	flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.1.jar) 
	UCH	framez{1.0.0} [Framez] (Framez3-pre2.jar) 
	UCH	gearswap{1.2.6} [Gear Swapper] (gearswap-1.10-1.2.6.jar) 
	UCH	inventorysorter{0.10.0+42} [Simple Inventory sorting] (inventorysorter-1.10-0.10.0+42.jar) 
	UCH	IronChest{7.0.6.794} [Iron Chest] (ironchest-1.10.2-7.0.6.794.jar) 
	UCH	journeymap{1.9.4-5.2.3} [JourneyMap] (journeymap-1.9.4-5.2.3-unlimited.jar) 
	UCH	jeresources{0.4.8.48} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.8.48.jar) 
	UCH	llor{1.0.7-mc1.10} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.10.jar) 
	UCH	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCH	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCE	moreoverlays{1.6} [MoreOverlays] (moreoverlays-1.6-mc1.9.4.jar) 
	UCH	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-4.jar) 
	UCH	Morpheus{1.10-3.1.6} [Morpheus] (Morpheus-1.10-3.1.6.jar) 
	UCH	notenoughwands{1.3.7} [Not Enough Wands] (notenoughwands-1.10-1.3.7.jar) 
	UCH	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UCH	playerrugs{1.9.4-1.3.2} [Player Rugs] (PlayerRugs-1.9.4-1.3.2.jar) 
	UCH	Quark{beta-49} [Quark] (Quark-beta-49.jar) 
	UCH	xreliquary{1.10.2-1.3.3.unstable} [Reliquary] (Reliquary-1.10.2-1.3.3.baublesfix.jar) 
	UCH	rflux{0.0.1} [RF Lux] (rflux-0.0.1.jar) 
	UCH	rftools{5.24} [RFTools] (rftools-1.10-5.24.jar) 
	UCH	rftoolscontrol{1.1.1} [RFTools Control] (rftoolsctrl-1.10-1.1.1.jar) 
	UCH	rftoolsdim{4.30beta50} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta50.jar) 
	UCH	roots{0.107} [Roots] (roots-0.107.jar) 
	UCE	Sampler{1.67} [Sampler] (sampler-1.67.jar) 
	UCH	shearmadness{1.10.2} [Shear Madness] (shearmadness-1.10.2-1.2.1.jar) 
	UCH	Signals{1.0} [Signals] (Signals-1.9.4-0.4.2-universal.jar) 
	UCH	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCH	StorageDrawers{1.9.4-3.1.10} [Storage Drawers] (StorageDrawers-1.9.4-3.1.10.jar) 
	UCH	rscircuits{0.0.1} [Super Circuit Maker] (SuperCircuitMaker-0.0.12.jar) 
	UCH	tails{1.10.2-1.8.2} [Tails] (Tails-1.10.2-1.8.2.jar) 
	UCH	theoneprobe{1.1.1a} [The One Probe] (theoneprobe-1.10-1.1.1a.jar) 
	UCH	Thump{@VERSION@} [Thump] (Thump-1.10.2-4.1.0.135.jar) 
	UCH	Zoology{1.0} [Zoology] (zoology-1.10-alpha-1.0.0.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.70-ex110.jar)
  
LoadingPlugin (Quark-beta-49.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (sampler-1.67.jar)
  
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.31-dev.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (sneakyhost-8.jar)
  sneakyhost.asm.SocketChannelReplacer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce GTX 680/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/E:/code/JustEnoughItems/run/mods/mcjtylib-1.10-2.1.3.jar!/cofh/api/energy/TileEnergyHandler.class
```

**Comment by kane-thornwyrd** [comment]
Please consider using [Gist](https://gist.github.com/)
