### ISSUE TITLE
Quark 2.3-265 crashing in Forge launcher

### ISSUE THREAD

**Issue by fzzyhmstrs** [Vazkii/AutoRegLib#52]
Using Quark r2.3-265 and Autoreglib 1.6-43. Getting the following crash. Also note that I had to manually add the respective licenses to the mods.toml file just to get this far. 

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/18/20 9:13 AM
Description: Initializing game

java.lang.NoSuchFieldError: field_239240_f_
	at vazkii.quark.tools.client.GlintRenderType.buildGlintDirectRenderType(GlintRenderType.java:94) ~[?:r2.3-265] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.tools.client.GlintRenderType.newRenderList(GlintRenderType.java:46) ~[?:r2.3-265] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.tools.client.GlintRenderType.<clinit>(GlintRenderType.java:27) ~[?:r2.3-265] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.base.handler.AsmHooks.addGlintTypes(AsmHooks.java:263) ~[?:r2.3-265] {re:classloading}
	at net.minecraft.client.renderer.RenderTypeBuffers.func_228486_a_(SourceFile) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-glint-types}
	at net.minecraft.client.renderer.RenderTypeBuffers.func_228485_a_(SourceFile:20) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-glint-types}
	at net.minecraft.util.Util.func_200696_a(SourceFile:351) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.RenderTypeBuffers.<init>(SourceFile:13) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-glint-types}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:455) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[minecraft-1.16.3-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.0-launcher.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at vazkii.quark.tools.client.GlintRenderType.buildGlintDirectRenderType(GlintRenderType.java:94) ~[?:r2.3-265] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.tools.client.GlintRenderType.newRenderList(GlintRenderType.java:46) ~[?:r2.3-265] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.tools.client.GlintRenderType.<clinit>(GlintRenderType.java:27) ~[?:r2.3-265] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.base.handler.AsmHooks.addGlintTypes(AsmHooks.java:263) ~[?:r2.3-265] {re:classloading}
	at net.minecraft.client.renderer.RenderTypeBuffers.func_228486_a_(SourceFile) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-glint-types}
	at net.minecraft.client.renderer.RenderTypeBuffers.func_228485_a_(SourceFile:20) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-glint-types}
	at net.minecraft.util.Util.func_200696_a(SourceFile:351) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.RenderTypeBuffers.<init>(SourceFile:13) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-glint-types}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:455) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) ~[minecraft-1.16.3-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.0-launcher.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1886730592 bytes (1799 MB) / 2299527168 bytes (2193 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5120m
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.0-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.0-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.0-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.0
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.0-client.jar Minecraft {minecraft@1.16.3 NONE}
		cleancut-mc1.16-2.2-forge.jar Clean Cut {cleancut@2.2 NONE}
		EnchantmentDescriptions-1.16.3-5.0.1.jar EnchantmentDescriptions {enchdesc@5.0.1 NONE}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 NONE}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 NONE}
		ImmersiveEngineering-1.16.3-4.1.0-124.jar Immersive Engineering {immersiveengineering@1.16.3-4.1.0-124 NONE}
		ironfurnaces-1.16.3-2.4.0.jar Iron Furnaces {ironfurnaces@2.4.0 NONE}
		clayconversion-1.16.x-1.4.jar Clay Conversion {clayconversion@1.4 NONE}
		SilentGear-1.16.3-2.3.0+165.jar Silent Gear {silentgear@2.3.0+165 NONE}
		jei-1.16.3-7.4.0.40.jar Just Enough Items {jei@7.3.2.29 NONE}
		metalbarrels-3.3a.jar Metal Barrels {metalbarrels@3.3a NONE}
		Ding-1.16.3-1.2.0.jar Ding {ding@1.2.0 NONE}
		TextDamageIndicators-1.16.3-2.0.1.jar TextDamageIndicators {textdamageindicators@2.0.1 NONE}
		goprone-1.16.3-1.3.5.jar GoProne {goprone@1.16.3-1.3.5 NONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 NONE}
		Quark-r2.3-265.jar Quark {quark@r2.3-265 NONE}
		Mantle-1.16.3-1.6.40.jar Mantle {mantle@1.6.40 NONE}
		Xaeros_Minimap_20.26.0_Forge_1.16.3.jar Xaero's Minimap {xaerominimap@20.26.0 NONE}
		gravestone-1.16.3-1.0.2.jar Gravestone Mod {gravestone@1.16.3-1.0.2 NONE}
		XaerosWorldMap_1.11.0_Forge_1.16.3.jar Xaero's World Map {xaeroworldmap@1.11.0 NONE}
		JRFTL+[1.16.3]-1.1.jar JRFTL {jrftl@1.1 NONE}
		FastWorkbench-1.16.3-4.4.0.jar FastWorkbench {fastbench@4.4.0 NONE}
		Controlling-7.0.0.8.jar Controlling {controlling@7.0.0.8 NONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 NONE}
		Placebo-1.16.3-4.3.2.jar Placebo {placebo@4.3.2 NONE}
		NaturesCompass-1.16.3-1.8.5.jar Nature's Compass {naturescompass@1.16.3-1.8.5 NONE}
		Ceramics-1.16.3-1.5.1.jar Ceramics {ceramics@1.5.1 NONE}
		VanillaTweaks-1.16.3-1.5.33.jar VanillaTweaks {vanillatweaks@1.16.3-1.5.33 NONE}
		Bookshelf-1.16.3-8.5.17.jar Bookshelf {bookshelf@8.5.17 NONE}
		repurpose-1.3.0.1.jar Repurpose {repurpose@1.3.0.1 NONE}
		guardvillagers-1.16.3-1.1.5.jar Guard Villagers {guardvillagers@1.1.5 NONE}
		FastFurnace-1.16.3-4.3.0.jar FastFurnace {fastfurnace@4.3.0 NONE}
		ForgivingVoid_1.16.3-5.2.0.jar Forgiving Void {forgivingvoid@5.2.0 NONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 NONE}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 NONE}
		Toast-Control-1.16.3-4.3.0.jar Toast Control {toastcontrol@4.3.0 NONE}
		SilentGems-1.16.1-3.6.3+100.jar Silent's Gems 3 {silentgems@3.6.3+100 NONE}
		forge-1.16.3-34.1.0-universal.jar Forge {forge@34.1.0 NONE}
		FastLeafDecay-v25.jar FastLeafDecay {fastleafdecay@v25 NONE}
		overloadedarmorbar-5.1.0.jar Overloaded Armor Bar {overloadedarmorbar@5.1.0 NONE}
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz

**Comment by fzzyhmstrs** [comment]
meant to leave in the Quark github
