### ISSUE TITLE
AutoRegLib 1.6-49 crashes on forge 1.17.1.load

### ISSUE THREAD

**Issue by leninkster** [Vazkii/AutoRegLib#63]
FML Loader runs, and fails after loading MC background, but BEFORE game option selection screen, with the following message:

_**AutoRegLib (autoreglib) has failed to load correctly
java.lang.NoClassDefFoundError:**_

![image](https://user-images.githubusercontent.com/9325780/130994441-7cd82215-14e0-4462-a9ed-7d85fc54c34f.png)

Sound is operational but cannot proceed from this error.  Closing the window is the only option. 

Removing the mod allows Forge 1.17.1 to start OK.

Error Log (relevant entry) is:

_**[11:46:00] [modloading-worker-2/INFO]: Forge mod loading, version 37.0.44, for MC 1.17.1 with MCP 20210706.113038
[11:46:00] [modloading-worker-2/INFO]: MinecraftForge v37.0.44 Initialized
[26Aug2021 11:46:00.861] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: autoreglib, class vazkii.arl.AutoRegLib
java.lang.NoClassDefFoundError: net/minecraftforge/common/capabilities/Capability$IStorage
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.17.1-37.0.44.jar%2356!:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.17.1-37.0.44.jar%2356!:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.17.1-37.0.44.jar%2356!:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.44.jar%2355!:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.capabilities.Capability$IStorage
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.46.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 14 more
[26Aug2021 11:46:12.994] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found**_

**Comment by agumetyusuftby** [comment]
Did you solve it? I need a lot of help.
